In [4]:
# prompt: import torch
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# print(torch.__version__)

!pip install torch
!pip install pandas
!pip install numpy
!pip install matplotlib

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.4.0+cu121


In [6]:
scalar = torch.tensor(7)
scalar

In [ ]:
scalar.ndim

In [ ]:
scalar.item()

In [ ]:
vector = torch.tensor([7, 7])

In [11]:
matrix = torch.tensor([[4, 5], [6, 7]])
matrix.ndim
matrix[1]
matrix.shape

torch.Size([2, 2])

In [18]:
tensor = torch.tensor([[[[1,2],
                        [3,4],
                        [5,6]],
                        [[7,8],
                         [9,10],
                          [11,12]]]])
tensor.ndim
tensor[0]

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [19]:
tensor.shape

torch.Size([1, 2, 3, 2])

In [22]:
random_tensor = torch.rand(1, 4, 3, 3)
print(random_tensor)

tensor([[[[0.6854, 0.6010, 0.4614],
          [0.0865, 0.5866, 0.3407],
          [0.3331, 0.5452, 0.4048]],

         [[0.9535, 0.8367, 0.3481],
          [0.2743, 0.7334, 0.1243],
          [0.2180, 0.2810, 0.3987]],

         [[0.3555, 0.4696, 0.2815],
          [0.7082, 0.4379, 0.3814],
          [0.7679, 0.1304, 0.5992]],

         [[0.1565, 0.7205, 0.9187],
          [0.6579, 0.4588, 0.4180],
          [0.3723, 0.1042, 0.2041]]]])


In [23]:
random_tensor.ndim

4

In [24]:
random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [25]:
print(random_image_tensor)

tensor([[[0.6929, 0.4191, 0.0045],
         [0.1218, 0.3627, 0.4921],
         [0.8601, 0.7370, 0.8836],
         ...,
         [0.1290, 0.6479, 0.6135],
         [0.2475, 0.8849, 0.2943],
         [0.0729, 0.0506, 0.9747]],

        [[0.5080, 0.1920, 0.2693],
         [0.9961, 0.2574, 0.1602],
         [0.4439, 0.0131, 0.5647],
         ...,
         [0.5507, 0.5802, 0.1057],
         [0.6553, 0.2736, 0.8842],
         [0.2419, 0.7633, 0.0329]],

        [[0.6250, 0.0116, 0.4938],
         [0.3020, 0.3675, 0.1364],
         [0.7715, 0.9295, 0.1853],
         ...,
         [0.4616, 0.8011, 0.8191],
         [0.7062, 0.4847, 0.5190],
         [0.1857, 0.5287, 0.8363]],

        ...,

        [[0.4967, 0.2760, 0.6043],
         [0.6722, 0.6894, 0.6237],
         [0.0705, 0.6941, 0.6325],
         ...,
         [0.3041, 0.7298, 0.0156],
         [0.8938, 0.8746, 0.2880],
         [0.2020, 0.9734, 0.6095]],

        [[0.0522, 0.1906, 0.8419],
         [0.3751, 0.4451, 0.4484],
         [0.

In [32]:
test = torch.rand(4, 4, 3)
print(test)

tensor([[[0.9867, 0.0694, 0.7614],
         [0.3948, 0.2373, 0.4917],
         [0.0727, 0.4039, 0.0548],
         [0.6668, 0.0171, 0.3669]],

        [[0.2083, 0.8999, 0.5423],
         [0.3045, 0.3131, 0.7982],
         [0.3621, 0.7539, 0.9323],
         [0.7235, 0.5999, 0.7757]],

        [[0.2824, 0.7254, 0.3925],
         [0.2929, 0.7009, 0.7093],
         [0.1388, 0.6860, 0.6283],
         [0.8922, 0.4961, 0.6004]],

        [[0.4336, 0.3288, 0.6340],
         [0.8947, 0.2950, 0.0766],
         [0.8165, 0.6570, 0.4042],
         [0.8129, 0.1044, 0.5230]]])


In [33]:
random_tensor_zeros = torch.zeros(size=(3, 4))
random_tensor_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])